sudo: true

before_install:
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq lyx
  - sudo apt-get install -qq texlive

script: 
 - ./build.sh